# Generated by Django 3.2 on 2023-07-26 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20230726_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ManyToManyField(blank=True, null=True, related_name='bidlisting', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='buyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='lisitngbuyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
