# Generated by Django 3.2 on 2023-07-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20230726_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auction',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidlisting', to='auctions.listing'),
        ),
        migrations.RemoveField(
            model_name='bids',
            name='buyer',
        ),
        migrations.AddField(
            model_name='bids',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingbuyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
