# Generated by Django 3.2 on 2023-07-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20230726_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auction',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ManyToManyField(blank=True, null=True, related_name='bidlisting', to='auctions.Listing'),
        ),
    ]
